@baseUrl = http://localhost:3001
@contentType = application/json

### Create a Account
GET {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "name": "Gabriel Gurris", 
    "email": "gabriel2gurris@outlook.com",
    "address": "Avenida itavuvu", 
    "naddress": "8944", 
    "neighborhood": "Distrito industrial", 
    "cep": "18000-899", 
    "phone1": "15997456321", 
    "phone2": "15997256389", 
    "password": "1234"
} 